### ISSUE TITLE
Not able to add new line inside cell

### ISSUE THREAD

**Issue by rahulsinghtoxsl** [yidas/phpspreadsheet-helper#10]
i tried below code to add a new line inside cell, but it not working.
` $time_till.'\n'.$request['time_till']`

**Comment by rahulsinghtoxsl** [comment]
Looks like this repo is not active..

**Comment by yidas** [comment]
Please describe your issue more specifically.

**Comment by Alf74570** [comment]
complete list of MIME types

List of MIME types
.xls | Microsoft Excel | application/vnd.ms-excel
.xlsx | Microsoft Excel (OpenXML) | application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

Your code : 
File : Helper.php
//Extension list for writer
'Xlsx' => [
    'extension' => '.xlsx',
    'contentType' => 'application/vnd.ms-excel'
 ],
 'Xls' => [
     'extension' => '.xls',
     'contentType' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
 ],

You must reverse contentType between 'xls' and 'xlsx'.
Thanks.

**Comment by yidas** [comment]
Hi @Alf74570,

This issue has been fixed at [version 1.3.6](https://github.com/yidas/phpspreadsheet-helper/releases/tag/1.3.6).

Thank you!

**Comment by Alf74570** [comment]
Thanks for your reactivity. Good job.
