### ISSUE TITLE
Cell format

### ISSUE THREAD

**Issue by wispoz** [yidas/phpspreadsheet-helper#2]
It possible set cell format to percent ?
And set some color or border to cell or cell group?

**Comment by yidas** [comment]
Percentage usage:

```php
\yidas\phpSpreadsheet\Helper::newSpreadsheet()
    ->addRow(['Percent', '10%'])
```

Styling feature would be the milestone for this lib.

Cheers

**Comment by wispoz** [comment]
Thx!
How about alignment of value
right - center - left  in cell?

**Comment by yidas** [comment]
Good suggestion.

Added to [Milestone](https://github.com/yidas/phpspreadsheet-helper/milestone/1)

**Comment by yidas** [comment]
https://github.com/yidas/phpspreadsheet-helper/releases/tag/1.2.2

**Comment by yidas** [comment]
Now [v1.3.0](https://github.com/yidas/phpspreadsheet-helper/releases/tag/1.3.0) supports defining attributes with a row, which the attributes include cell format features from `style` key.

With these methods, the  implementation of cell format is even simpler.
