### ISSUE TITLE
Chart integration

### ISSUE THREAD

**Issue by wispoz** [yidas/phpspreadsheet-helper#3]
Its possible set chart?

**Comment by yidas** [comment]
Chart could be insert as graph into Excel:

[PHPSpreadsheet - Add a drawing to a worksheet](https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/docs/topics/recipes.md#add-a-drawing-to-a-worksheet).
You could integrate drawing with helper by [PhpSpreadsheet Original Usage Integration](https://github.com/yidas/phpspreadsheet-helper#phpspreadsheet-original-usage-integration)

In the another hand, [Rendering charts](https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/docs/topics/migration-from-PHPExcel.md#rendering-charts) could be implement for HTML or PDF outputs.

Cheers
