### ISSUE TITLE
how i can get column by head 

### ISSUE THREAD

**Issue by vahidalvandi** [yidas/phpspreadsheet-helper#8]
for example 
$rows->getRow()
work like
`$amount= $rows->getRow('amout')`
??

**Comment by yidas** [comment]
Hi @vahidalvandi,

You can try:

```
$amount= $rows->getRow()[0];
```

Which `0` is the array key referred to column number.

Cheers

**Comment by vahidalvandi** [comment]
how i get with column number
![image](https://user-images.githubusercontent.com/7871623/52900022-45938880-3206-11e9-8dae-900677d3388a.png)

get user_id  or amount

**Comment by yidas** [comment]
For your case:

```php
$helper->getRow(); // Skip header
while ($row = $helper->getRow()) {
    echo "user_id: {$row[0]} | amount: {$row[1]}\n";
}
```

> `0` is referred to `A` column, `1` => `B`.

BTW, you can also use [getrows()](https://github.com/yidas/phpspreadsheet-helper#getrows) to find out by sequence.

**Comment by vahidalvandi** [comment]
i need a command return just cloum amount in each row

**Comment by yidas** [comment]
```php
$dataArray = $helper->getSheet()
    ->rangeToArray(
        'B2:B3',     // The worksheet range that we want to retrieve
        NULL,        // Value that should be returned for empty cells
        TRUE,        // Should formulas be calculated (the equivalent of getCalculatedValue() for each cell)
        TRUE,        // Should values be formatted (the equivalent of getFormattedValue() for each cell)
        TRUE         // Should the array be indexed by cell row and cell column
    );
```
